[tools]
bun = "1.3"
"cargo:wasm-opt" = "0.116"
"cargo:wasm-pack" = "0.13"
node = "24"
rust = "1.81"
tilt = "0.35"

[env]
_.path = [
  # adds paths relative to directory in which this file was found (see below for details), not PWD
  "{{config_root}}/node_modules/.bin",
]
TILT_PORT = "10308"

[tasks."wasm:build"]
description = "Build WASM module for production"
run = "wasm-pack build --target web --out-dir pkg"
sources = ["src-rust/**/*.rs", "Cargo.toml"]
outputs = ["pkg/*.js", "pkg/*.wasm", "pkg/*.ts"]

[tasks."wasm:dev"]
description = "Build WASM module for development"
run = "wasm-pack build --dev --target web --out-dir pkg"
sources = ["src-rust/**/*.rs", "Cargo.toml"]
outputs = ["pkg/*.js", "pkg/*.wasm", "pkg/*.ts"]

[tasks.dev]
description = "Run development server with WASM rebuild"
run = "vite"
# no sources, since this is a long running command

[tasks.build]
description = "Build for production"
depends = ["wasm:build"]
run = "vite build"
sources = ["src/**/*", "vite.config.mts", "tsconfig.json"]
outputs = ["build/**/*"]

[tasks.preview]
description = "Preview production build locally"
depends = ["build"]
run = "bunx serve ./build"

[tasks.typecheck]
description = "Type check TypeScript files"
depends = ["codegen:typescript"]
run = "tsgo --build ."
sources = ["src/**/*", "tsconfig.json", "package.json", "bun.lock"]

[tasks.server]
description = "Run WebSocket server"
run = "cargo run -p pathfinder-server"

[tasks."wasm:watch"]
description = "Watch and rebuild WASM on changes"
run = "mise watch -t wasm:dev"

[tasks.tilt]
alias = "up"
description = "Start Tilt development environment"
run = "tilt up"

[tasks."tilt:down"]
description = "Stop Tilt and clean up resources"
run = "tilt down"

[tasks."codegen:typescript"]
description = "Generate TypeScript types from Rust types"
run = "cargo test --features codegen generate_typescript -- --ignored"
sources = ["src-rust/**/*.rs", "Cargo.toml", "cg-types/generators/*.ts", "cg-types/src/**/*.rs"]
outputs = ["cg-types/generators/gen/**/*", "generators/**/*"]

# Uncomment to pin tool versions
# node = "22"
# rust = "latest"
